---
- name: Configure App
  hosts: app
  become: true
  vars:
    db_host: 35.228.102.215
  tasks:

    - name: Add unit file for Puma
      copy: 
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Change database config file for app connections
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
    - name: reload puma
      systemd: name=puma state=restarted
